#!/usr/bin/env bash

source <(curl -s https://archibold.io/benja/utils)

clear
targetPlatform

clear
findTheDisk

if [ ! -f "${BENJA_ARCHIVE}" ]; then
  clear
  echoWithLogo "# Downloading ${BENJA_SBC} Archive
"

  curl -LO "http://os.archlinuxarm.org/os/${BENJA_ARCHIVE}"
fi

BENJA_ARCHIVE_PATH="$(pwd)/${BENJA_ARCHIVE}"

clear
echoWithLogo "# Preparing ${BENJA_SBC} Card

  * partitioning
  * formatting
  * copy files over
"
BENJA_SD_SIZE=$(sudo fdisk -s $BENJA_DISK)
BENJA_ROOT_SIZE="6800000"
if [ $BENJA_ROOT_SIZE \> $BENJA_SD_SIZE ]; then
  BENJA_ROOT_SIZE="3800M"
else
  BENJA_ROOT_SIZE="6800M"
fi

echomd "*SD Card info*
  * total space: $BENJA_SD_SIZE
  * root partition of $BENJA_ROOT_SIZE

# WARNING

  disk *${BENJA_DISK}* will be completely *erased*
  #red(all data) in it will be #red(lost)
"
read -n1 -r -p "$(echomd " erase *${BENJA_DISK}* ? [y/N]")" CHOICE

if [[ $? -ne 0 ]] || [ "$CHOICE" != "y" ]; then
  echo ""
  echomd "*bye bye*"
  echo ""
  exit 1
fi

clear
echoWithLogo "# Preparing ${BENJA_SBC} Card

  * partitioning
"
sudo umount $BENJA_DISK* 2> /dev/null
createPartitions "${BENJA_DISK}" "$BENJA_ROOT_SIZE"

clear
echoWithLogo "# Preparing ${BENJA_SBC} Card

  * partitioning ✔
  * formatting
"
BENJA_SDCARD_PARTITIONS=($(getPartitions $BENJA_DISK))
formatPartitions "$BENJA_DISK" ${BENJA_SDCARD_PARTITIONS[*]}

clear
echoWithLogo "# Preparing ${BENJA_SBC} Card

  * partitioning ✔
  * formatting ✔
  * copy files over

  This operation might take a while, please wait
"
mkdir -p ~/tmp-mounting-point
cd ~/tmp-mounting-point
installOS "$BENJA_ARCHIVE_PATH" "$BENJA_DISK" ${BENJA_SDCARD_PARTITIONS[*]}
cd -
sync
cd ~/tmp-mounting-point/root/home/alarm

clear
echoWithLogo "# Preparing ${BENJA_SBC} Card

  * partitioning ✔
  * formatting ✔
  * copy files over ✔

  Downloading bootstrap
"
echo '#!/usr/bin/env bash

echo "BENJA setup starting in 3 seconds"
sleep 3

if ! curl --output /dev/null --silent --fail -r 0-0 "http://archibold.io/"; then
  ./wifi-setup
fi

if ! curl --output /dev/null --silent --fail -r 0-0 "http://archibold.io/"; then
  echo "Unable to reach the internet."
  echo "Try ./wifi-setup or attach a network cable."
  exit 1
fi

if [ "$(which ntpdate 2> /dev/null)" != "" ]; then
  echo -e "Updating time, \x1B[1mno password needed\x1B[22m, please wait ..."
  echo root | su -c "ntpdate pool.ntp.org
timedatectl set-local-rtc 1"
fi
' > bootstrap
curl -s "https://archibold.io/benja/setup/${BENJA_SETUP}" >> bootstrap
chmod a+x bootstrap

curl -s "https://archibold.io/benja/setup/benja_wifi" > wifi-setup
chmod a+x wifi-setup
cd -

clear
echoWithLogo "# ${BENJA_SBC} Card Ready 🎉

  * plugin the SD card into the ${BENJA_SBC}
  * login via user *alarm* and password *alarm*
  * type *./bootstrap* once logged in

  Thank you for using B.E.N.J.A.
"
sync
sudo umount $BENJA_DISK* 2> /dev/null
sleep 1
rm -rf ~/tmp-mounting-point
