#!/usr/bin/bash

commonProcedure() {
  local type=$1
  local name=$2
  sudo pacman -S --needed --noconfirm base-devel git
  cd ~/Downloads
  curl -O "https://aur.archlinux.org/packages/${type}/${name}/${name}.tar.gz"
  tar -xzf "${name}.tar.gz"
  cd "${name}"
  makepkg -Asc --needed --noconfirm
  sudo pacman -U --needed --noconfirm ${name}*.pkg.tar.xz
  cd ..
  rm -rf "${name}"
  rm "${name}.tar.gz"
}

installation() {
  case $1 in
    google-chrome-dev)
      commonProcedure 'go' 'google-chrome-dev'
      ;;
    spotify)
      commonProcedure 'li' 'libgcrypt15'
      commonProcedure 'sp' 'spotify'
      ;;
    sublime-text-nightly)
      commonProcedure 'su' 'sublime-text-nightly'
      ;;
    *)
      echo '
 - - - - - - -
| aur  v0.0.1 |
 - - - - - - -
 list of programs:

   aur google-chrome-dev
   aur spotify
   aur sublime-text-nightly

'
      ;;
  esac
}

installation $1
