#!/usr/bin/bash

commonProcedure() {
  local type=$1
  local name=$2
  sudo pacman -S --needed --noconfirm base-devel git
  cd ~/Downloads
  curl -O "https://aur.archlinux.org/packages/${type}/${name}/${name}.tar.gz"
  tar -xzf "${name}.tar.gz"
  cd "${name}"
  makepkg -Asc --needed --noconfirm
  sudo pacman -U --needed --noconfirm ${name}*.pkg.tar.xz
  cd ..
  rm -rf "${name}"
  rm "${name}.tar.gz"
}

installation() {
  case $1 in
    install)
      installation $2
      ;;
    remove)
      sudo pacman -Rsc $2
      ;;
    broadcom-wl-dkms)
      sudo pacman -Syu --needed linux-headers dkms
      sudo systemctl enable dkms.service
      commonProcedure 'br' 'broadcom-wl-dkms'
      ;;
    google-chrome-dev)
      commonProcedure 'go' 'google-chrome-dev'
      ;;
    spotify)
      commonProcedure 'li' 'libgcrypt15'
      commonProcedure 'sp' 'spotify'
      ;;
    sublime-text-nightly)
      commonProcedure 'su' 'sublime-text-nightly'
      ;;
    *)
      echo '
 - - - - - - -
| aur  v0.0.2 |
 - - - - - - -

 usage:

  aur [install|remove] program-name
  aur program-name # implicit install


 list of programs:

  broadcom-wl-dkms        # broadcom wifi
  google-chrome-dev       # dev channel
  spotify                 # music baby!
  sublime-text-nightly    # sublime 3

'
      ;;
  esac
}

installation $1 $2
