#!/usr/bin/env bash

sudo pacman -S --needed --noconfirm \
  fbset sed grep npm \
  xf86-video-intel xf86-input-synaptics \
  xorg-server xorg-xinit \
  libxrandr libxinerama libxcursor libxtst \
  gnome-themes-standard gtk-engines \
  libnotify gconf nss alsa-plugins

# configure npm
if [ ! -d ~/.npm-packages/bin ]; then
  mkdir -p ~/.npm-packages/bin
  npm config set prefix '~/.npm-packages'
  echo '
# npm and nodejs global modules
export PATH="$PATH:$HOME/.npm-packages/bin"
export NODE_PATH="$NODE_PATH:$HOME/.npm-packages/lib/node_modules"
'>>~/.bashrc
  source ~/.bashrc
fi

if [ ! -f ~/www/package.json ]; then
  mkdir -p ~/www

  echo '{
  "name"    : "SinonOS",
  "version" : "0.0.1",
  "main"    : "main.js"
}'>~/www/package.json

  echo "'use strict';

const
  electron  = require('electron'),
  app = electron.app,
  BrowserWindow = electron.BrowserWindow
;

var mainWindow = null;

app
  .on('window-all-closed', function() {
    if (process.platform != 'darwin') app.quit();
  })
  .on('ready', function() {
    mainWindow = new BrowserWindow({
      width: process.env.WIDTH,
      height: process.env.HEIGHT
    });
    mainWindow.loadURL('file://' + __dirname + '/index.html');
    // mainWindow.webContents.openDevTools();
    mainWindow.on('closed', function() {
      mainWindow = null;
    });
  });
">~/www/main.js

  echo '<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>SinonOS</title>
  </head>
  <body>
    We are using node <script>document.write(process.versions.node)</script>,
    Chrome <script>document.write(process.versions.chrome)</script>,
    and Electron <script>document.write(process.versions.electron)</script>.
  </body>
</html>'>~/www/index.html
fi

if [ ! -f ~/.xinitrc ];then
  echo "WIDTH=$(sudo fbset | grep 'mode ' | sed -e 's/mode "//' | sed -e 's/x.*//') HEIGHT=$(sudo fbset | grep 'mode ' | sed -e 's/mode "[0-9]*x//' | sed -e 's/"//') electron ~/www/">~/.xinitrc
fi

npm install -g electron-prebuilt

startx -- vt1 &> /dev/null