#!/usr/bin/env bash

##############################
# archibold.io (C) 2016-2020 #
##############################
#
# arch-chroot env
#
# LABEL
# LANGUAGE
# DISK
# BOOT
# SWAP
# ROOT
# UEFI
# USER
# PASSWORD
# EDD
# QUIET
# ENCRYPTION
# GNOME
#

source <(curl -s https://archibold.io/utils/partid)

cleanEfibootmgr() {
  local which="$1"
  local prev=
  for entry in $(efibootmgr); do
    if [ "$entry" = "$which" ]; then
      efibootmgr -b "${prev:4:-1}" -B
    fi
    prev="$entry"
  done
}

echo -e "
  generating $(tput bold)locale$(tput sgr0)
"

if [ "$LANGUAGE" != "en" ]; then
  sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
fi
sed -i -r "s/^#(${LANGUAGE}_.*? UTF-8)/\1/" /etc/locale.gen
locale-gen
locale > /etc/locale.conf

echo -e "
  installing $(tput bold)linux$(tput sgr0)
"

pacman-key --init
pacman-key --populate archlinux
pacman -S --needed --noconfirm pacman-mirrorlist linux linux-headers linux-firmware mkinitcpio vi
sync

if [ "$ENCRYPTION" = "yes" ]; then
  echo -e "
  preparing  $(tput bold)encryption$(tput sgr0)
"

  echo "build ()
{
  add_binary blkid
  add_binary cryptsetup
  add_binary echo
  add_binary mkdir
  add_runscript
}
help ()
{
cat<<HELPEOF
  This asks for the encryption password once and then opens root and swap
HELPEOF
}" > /etc/initcpio/install/archibold

  UUID="$(partid $ROOT)"
  echo "run_hook ()
{
  echo -e \"Please enter your \033[1mencryption\033[0m password:\"
  mkdir -p /run/cryptsetup
  local password=
  local i=0
  while [ \$i -lt 3 ]; do
    i=\$((i+1))
    read -s -r password
    echo \"\$password\" | sh -c 'cryptsetup open \$(blkid --uuid \"$UUID\") root'
    if [[ \$? -eq 0 ]]; then
      i=3
      echo -e \"password \033[1mOK\033[0m\"" > /etc/initcpio/hooks/archibold
  if [ "$SWAP" != "0" ]; then
    UUID="$(partid $SWAP)"
    echo "      echo \"\$password\" | sh -c 'cryptsetup open \$(blkid --uuid \"$UUID\") swap'" >> /etc/initcpio/hooks/archibold
  fi
  echo "    else
      if [ \$i -eq 3 ]; then
        echo -e \"\033[1mtoo many wrong passwords\033[0m\"
      else
        echo -e \"\033[1mwrong\033[0m password, please try again:\"
      fi
    fi
  done
}" >> /etc/initcpio/hooks/archibold
  # apparently consolefont was useless
  if [ "$SWAP" != "0" ]; then
    sed -i -r 's/^(HOOKS=.*)/#\1\nHOOKS=(base udev autodetect keyboard keymap modconf block archibold encrypt resume filesystems fsck)/' /etc/mkinitcpio.conf
  else
    sed -i -r 's/^(HOOKS=.*)/#\1\nHOOKS=(base udev autodetect keyboard keymap modconf block archibold encrypt filesystems fsck)/' /etc/mkinitcpio.conf
  fi
  mkinitcpio -p linux
else
  if [ "$SWAP" != "0" ]; then
    sed -i -r 's/^(HOOKS=.*)/#\1\nHOOKS=(base udev autodetect modconf block resume filesystems keyboard fsck)/' /etc/mkinitcpio.conf
    mkinitcpio -p linux
  fi
fi

echo -e "
  installing $(tput bold)wifi/net tools$(tput sgr0)
"

# TODO: I am not sure wireless-regdb is useful at all ...
pacman -S --needed --noconfirm dialog wpa_supplicant iw netctl dhcpcd wireless-regdb

UCODE=''
UCODE_STRING=''
if [ "$(cat /proc/cpuinfo | grep GenuineIntel)" != "" ]; then
  UCODE='intel-ucode'
elif [ "$(cat /proc/cpuinfo | grep AuthenticAMD)" != "" ]; then
  UCODE='amd-ucode'
fi
if [ "$UCODE" != "" ]; then
  UCODE_STRING="initrd  /${UCODE}.img
"
  echo -e "
  installing $(tput bold)${UCODE}$(tput sgr0)
"
  pacman -S --needed --noconfirm $UCODE
fi

if [ "$UEFI" = "efi32" ] || [ "$UEFI" = "efi64" ]; then
  echo -e "
  installing $(tput bold)UEFI$(tput sgr0) tools
"
  pacman -S --needed --noconfirm efibootmgr efitools
fi

if [ "$SWAP" != "0" ]; then
  echo -e "
  creating  $(tput bold)swap$(tput sgr0)
"
  if [ "$ENCRYPTION" = "yes" ]; then
    swapon /dev/mapper/swap
  else
    swapon $SWAP
  fi
fi

echo -e "
  generating $(tput bold)fstab$(tput sgr0)
"

genfstab -U -p / > /etc/fstab

sync
sed -i -r 's/^(# )?(\/etc|efivarfs).*//' /etc/fstab

if [ "$ENCRYPTION" = "yes" ]; then
  APPEND="options root=/dev/mapper/root rw"
  if [ "$SWAP" != "0" ]; then
    APPEND="$APPEND resume=/dev/mapper/swap rw"
  fi
  if [ "$BOOT_LOUDLY" = "" ]; then
    APPEND="$APPEND quiet loglevel=0"
  fi
else
  UUID="$(partid $ROOT)"
  APPEND="options root=UUID=${UUID} rw"
  if [ "$SWAP" != "0" ]; then
    UUID="$(partid $SWAP)"
    APPEND="$APPEND resume=UUID=${UUID} rw"
  fi
  if [ "$BOOT_LOUDLY" = "" ]; then
    APPEND="$APPEND quiet splash loglevel=0"
  fi
fi

if [ "$EDD" != "" ]; then
  APPEND="$APPEND edd=$EDD"
fi

if [ "$UEFI" = "efi32" ] || [ "$UEFI" = "efi64" ]; then
  echo -e "
  cleaning $(tput bold)efi$(tput sgr0) variables, if any
"
  cleanEfibootmgr "$LABEL"
fi

echo -e "
  preparing $(tput bold)bootctl$(tput sgr0)
"

bootctl --path=/boot install

echo "title   ${LABEL}
linux   /vmlinuz-linux
${UCODE_STRING}initrd  /initramfs-linux.img
${APPEND}" > /boot/loader/entries/arch.conf

echo -e "
  assigning $(tput bold)root$(tput sgr0) passwords
"

yes "$PASSWORD" | passwd

echo -e "
  creating user $(tput bold)$USER$(tput sgr0)
"

useradd -m -g users -G wheel,games,power,optical,storage,scanner,lp,audio,video -s /bin/bash $USER

echo -e "
  assigning $(tput bold)$USER$(tput sgr0) passwords
"

yes "$PASSWORD" | passwd $USER

echo -e "
  installing $(tput bold)so$(tput sgr0) helper
"

curl -LOs https://archibold.io/utils/so
chmod a+x so
mv so /usr/bin

echo -e "
  installing $(tput bold)aur$(tput sgr0) helper
"

curl -LOs https://archibold.io/utils/aur
chmod a+x aur
mv aur /usr/bin

if [ "$(which hwclock 2> /dev/null)" != "" ]; then
  echo -e "
  updating $(tput bold)time$(tput sgr0)
"
  hwclock --systohc --utc
fi

echo -e "
  executing $(tput bold)sync$(tput sgr0)
"

sync

if [ "$GNOME" = "yes" ]; then
  echo -e "
  installing $(tput bold)GNOME$(tput sgr0)
"
  runuser -l $USER -c "
export SUDO_PASSWORD='$PASSWORD'
bash <(curl -s https://archibold.io/install/gnome)
"

  # TODO: I'd love to get rid of the root user password but it cannot be done
  #       at this point, otherwise GNOME cannot be installed on boot.
  # passwd -d root

fi

echo -e "
  dropping $(tput bold)swap$(tput sgr0)
"

if [ "$ENCRYPTION" = "yes" ]; then
  swapoff /dev/mapper/swap
else
  swapoff $SWAP
fi

exit
