#!/usr/bin/env bash

# (c) 2018 Andrea Giammarchi - @WebReflection - (ISC)

while ! pacman -S --needed xorg-server xorg-xinit xorg-xset xorg-xrandr unclutter \
                              xf86-video-fbdev \
                              alsa-utils libcanberra \
                              gjs gnome-themes-extra \
                              webkit2gtk gst-plugins-base gst-plugins-good \
                              gstreamer-vaapi \
                              gst-libav gst-plugins-ugly \
                              geoip geoclue
do
  :
done
