#!/usr/bin/env bash

# (c) 2018 Andrea Giammarchi - @WebReflection - (ISC)

while ! pacman -S --needed --noconfirm \
                              weston \
                              xorg-server xorg-xinit xorg-xset xorg-xrandr \
                              alsa-utils libcanberra-gstreamer libcanberra-pulse \
                              gst-plugins-base gst-plugins-good \
                              gstreamer-vaapi \
                              gst-libav gst-plugins-ugly gst-plugins-bad \
                              geoip geoclue
do
  :
done
