echo "# x11 configuration

# to change resolution *
# * WIDTHxHEIGTH must be compatible with your screen
# xrandr -s 1280x720

# avoid sleep
xset s off -dpms

# unclutter the cursor then browse a generic page *
# * if you install nodejs bootstrap replace ./.browse ... with npm start
unclutter &
./.browse --fullscreen file:///home/alarm/www/index.html

# in case you'd like to see if it's hardware accelerated, try one of these
# ./.browse --bgcolor=0,0,0 --fullscreen https://threejs.org/examples/webgl_geometry_cube.html
# ./.browse --fullscreen https://www.youtube.com/watch?v=IlVtF3dAyxs
# ./.browse --fullscreen https://smashcat.org/av/canvas_test/
# ./.browse --fullscreen https://webkit.org/blog-files/3d-transforms/poster-circle.html
# ./.browse --fullscreen http://demo.kaazing.com/racer/
">.xinitrc
chown alarm:alarm .xinitrc