#!/usr/bin/env bash

# (c) 2018 Andrea Giammarchi - @WebReflection - (ISC)

if [ "$USER" != "root" ]; then
  echo "you need to be $(tput bold)root$(tput sgr0)";
  exit 1;
fi

cd /home/alarm
usermod -a -G video alarm

# bootstrap pacman
bash <(curl -s archibold.io/kiosk/utils/init)

# install specific driver
pacman -S --needed --noconfirm \
  odroid-c2-libgl-fb xf86-video-fbturbo-odroid-c2-git

# install all dependencies and optimize
bash <(curl -s archibold.io/kiosk/utils/dependencies)

# automatic login
bash <(curl -s archibold.io/kiosk/utils/login)

# download a minimalistic full screen browser
bash <(curl -s archibold.io/kiosk/utils/browser)

# setup the xinitrc
bash <(curl -s archibold.io/kiosk/utils/xinitrc)

# bootstrap xorg from .bashrc
bash <(curl -s archibold.io/kiosk/utils/bashrc)

# avoid initial message
touch .hushlogin
chown alarm:alarm .hushlogin

reboot
