#!/usr/bin/env bash


yes root | su -c 'mkdir -p /etc/systemd/system/getty@tty1.service.d'
yes root | su -c 'echo "[Service]
ExecStart=
ExecStart=-/usr/sbin/agetty -nia alarm %I
">/etc/systemd/system/getty@tty1.service.d/override.conf'

yes root | su -c 'echo "dtoverlay=vc4-fkms-v3d,cma-384
gpu_mem=128
gpu_mem_256=128
gpu_mem_512=196
gpu_mem_1024=384
initramfs initramfs-linux.img followkernel
dtparam=audio=on
dtparam=spi=on
dtparam=i2c_arm=on
dtparam=i2c=on
[all]
avoid_warnings=1
disable_splash=1
boot_delay=0
">/boot/config.txt'

echo '
if [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  weston-launch
fi
'>>~/.bashrc

yes root | su -c 'pacman-key --init'
yes root | su -c 'pacman-key --populate archlinuxarm'
yes root | su -c 'pacman -Syu --needed --noconfirm weston'

yes root | su -c 'groupadd weston-launch'
yes root | su -c 'usermod -a -G wheel,games,power,optical,storage,scanner,lp,audio,video,weston-launch alarm'

if [ -f /boot/boot.txt ]; then
  yes root | su -c 'pacman -S --needed --noconfirm uboot-tools'
  yes root | su -c 'sed -i "s/rootwait/rootwait quiet loglevel=0 cma=384MB@128MB/" /boot/boot.txt'
  yes root | su -c 'mkimage -T script -C none -n "Raspberry Pi" -d /boot/boot.txt /boot/boot.scr'
fi

if [ -f /boot/cmdline.txt ]; then
  yes root | su -c 'sed -i "s/rootwait/rootwait quiet loglevel=0 cma=384MB@128MB/" /boot/cmdline.txt'
fi

yes root | aur snapd

yes root | su -c 'systemctl enable snapd'
yes root | su -c 'systemctl start snapd'

yes root | su -c 'snap install mir-kiosk'
yes root | su -c 'snap install wpe-webkit-mir-kiosk'
yes root | su -c 'snap set wpe-webkit-mir-kiosk url=https://mir-server.io'
# yes root | su -c 'snap set mir-kiosk daemon=true'
# yes root | su -c 'snap restart mir-kiosk'

yes root | su -c reboot
