#!/usr/bin/env bash

if [ -f /boot/boot.txt ] && [ "$(cat /boot/boot.txt | grep 'rootwait quiet')" = "" ]; then
  while ! sudo pacman -S --needed --noconfirm uboot-tools
  do
    :
  done
  sudo sed -i 's/rootwait/rootwait quiet loglevel=0 cma=384MB@128MB/' /boot/boot.txt
  sudo mkimage -T script -C none -n 'Raspberry Pi' -d /boot/boot.txt /boot/boot.scr
fi

if [ -f /boot/cmdline.txt ] && [ "$(cat /boot/cmdline.txt | grep 'rootwait quiet')" = "" ]; then
  sudo sed -i 's/rootwait/rootwait quiet loglevel=0 cma=384MB@128MB/' /boot/cmdline.txt
fi

sudo sh -c "echo 'dtoverlay=vc4-fkms-v3d,cma-384

gpu_mem=128
gpu_mem_256=128
gpu_mem_512=196
gpu_mem_1024=384

initramfs initramfs-linux.img followkernel

dtparam=audio=on
dtparam=spi=on
dtparam=i2c_arm=on
dtparam=i2c=on

avoid_warnings=1
disable_splash=1
disable_overscan=1
boot_delay=0
'>/boot/config.txt"
