#!/usr/bin/env bash

# (c) 2018 Andrea Giammarchi - @WebReflection - (ISC)

if [ "$USER" != "root" ]; then
  echo "you need to be $(tput bold)root$(tput sgr0)";
  exit 1;
fi

cd /home/alarm
usermod -a -G video alarm

# bootstrap pacman
bash <(curl -s https://archibold.io/kiosk/utils/init)

# enable full kms driver and audio
echo "
dtoverlay=vc4-fkms-v3d
dtparam=audio=on
">>/boot/config.txt

if [ -f /boot/boot.txt ]; then
  # modify boot.scr to reserve cma memory and make the boot silent
  while ! pacman -S --needed --noconfirm uboot-tools
  do
    :
  done
  sed -i "s/rootwait/rootwait quiet loglevel=0 splash cma=128MB@64MB/" /boot/boot.txt
  # sed -i "s/rootwait/rootwait cma=128MB@64MB/" /boot/boot.txt
  mkimage -T script -C none -n "RPi3 VC4" -d /boot/boot.txt /boot/boot.scr
else
  # modify cmdline.txt mostly to make the boot silent (cma might be ignored)
  sed -i "s/rootwait/rootwait quiet loglevel=0 splash cma=128MB@64MB/" /boot/cmdline.txt
fi

# install specific driver
while ! pacman -S --needed --noconfirm \
  mesa libva-vdpau-driver libva-mesa-driver xf86-video-fbdev mesa-vdpau
do
  :
done

# install all dependencies and optimize
bash <(curl -s https://archibold.io/kiosk/utils/dependencies)

# automatic login
bash <(curl -s https://archibold.io/kiosk/utils/login)

# download a minimalistic full screen browser
bash <(curl -s https://archibold.io/kiosk/utils/browser)

# setup the xinitrc
bash <(curl -s https://archibold.io/kiosk/utils/xinitrc)

# bootstrap xorg from .bashrc
bash <(curl -s https://archibold.io/kiosk/utils/bashrc)

# avoid initial message
touch .hushlogin
chown alarm:alarm .hushlogin

reboot
