#!/usr/bin/env bash

if [ "$USER" != "root" ]; then
  echo "you need to be $(tput bold)root$(tput sgr0)";
  exit 1;
fi

cd /home/alarm

# update the system and the mirrors list
pacman -Sy --needed --noconfirm pacman-mirrorlist

# update the rest of the software
pacman -Su --noconfirm

# enable full kms driver and audio
echo "
dtoverlay=vc4-fkms-v3d
dtparam=audio=on
">>/boot/config.txt

# modify boot.scr to reserve cma memory and make the boot silent
pacman -S --needed --noconfirm uboot-tools
sed -i "s/rootwait/rootwait quiet loglevel=0 splash cma=128MB@64MB/" /boot/boot.txt
# sed -i "s/rootwait/rootwait cma=128MB@64MB/" /boot/boot.txt
mkimage -T script -C none -n "RPi3 VC4" -d /boot/boot.txt /boot/boot.scr

# automatic login
mkdir -p /etc/systemd/system/getty@tty1.service.d
echo "[Service]
ExecStart=
ExecStart=-/usr/sbin/agetty -nia alarm %I
">/etc/systemd/system/getty@tty1.service.d/override.conf

# install graphic drivers (watch out info about your card)
pacman -S --needed --noconfirm mesa libva-vdpau-driver libva-mesa-driver

# install X11
pacman -S --needed --noconfirm xorg-server xorg-xinit xf86-video-fbdev

# install xorg utilities
pacman -S --needed --noconfirm xorg-xset xorg-xrandr unclutter

# install alsa utils
pacman -S --needed --noconfirm alsa-utils

# install Gtk via GJS bindings + standard themes
pacman -S --needed --noconfirm gjs gnome-themes-standard

# and also latest WebKit (it's really good!)
pacman -S --needed --noconfirm webkit2gtk gst-plugins-base gst-plugins-good

# optional: gstreamer-vaapi for HW acceleration
pacman -S --needed gstreamer-vaapi

# optional: contains non-free software 
pacman -S --needed --noconfirm gst-libav gst-plugins-ugly

# download a minimalistic full screen browser
# curl -L bit.ly/2HPq5Nq -o browse ... or ...
curl -L archibold.io/test/gjs/browser -o .browse
chmod a+x .browse
chown alarm:alarm .browse

# create www/index.html
mkdir -p www
echo '<!doctype html><h1>RPi3 Web Kiosk</h1><pre>'>www/index.html
ip addr>>www/index.html
echo '</pre>'>>www/index.html
chown -R alarm:alarm www

# setup the xinitrc
echo "# x11 configuration

# to change resolution
# (WIDTHxHEIGTH must be compatible with your screen)
# xrandr -s 1280x720

# avoid sleep
xset s off -dpms

# unclutter the cursor then browse a generic page
unclutter &
./.browse --fullscreen file:///home/alarm/www/index.html">.xinitrc
# in case you'd like to see if it's hardware accelerated
# ./.browse --bgcolor=0,0,0 --fullscreen https://threejs.org/examples/webgl_geometry_cube.html">.xinitrc
# ./.browse --bgcolor=0,0,0 --fullscreen https://www.youtube.com/watch?v=IlVtF3dAyxs">.xinitrc
chown alarm:alarm .xinitrc

# bootstrap xorg from .bashrc
echo '
# startx on login
[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx > /dev/null 2>&1'>>.bashrc
chown alarm:alarm .bashrc

# avoid initial message
touch .hushlogin
chown alarm:alarm .hushlogin

# optimize and reboot
pacman-optimize
reboot
