#!/usr/bin/env bash

if [ "$USER" != "root" ]; then
  echo "you need to be $(tput bold)root$(tput sgr0)";
  exit 1;
fi

cd /home/alarm

# update the system and the mirrors list
pacman -Sy --needed --noconfirm pacman-mirrorlist

# update the rest of the software
pacman -Su --noconfirm

# enable GPU memory and vc4
echo "
gpu_mem=256
dispmanx_offline=1
dtoverlay=vc4-fkms-v3d
dtparam=audio=on
">>/boot/config.txt

# modify boot.scr to reserve cma memory and make the boot silent
pacman -S --needed --noconfirm uboot-tools
sed -i "s/rootwait/rootwait quiet loglevel=0 splash cma=256MB/" /boot/boot.txt
mkimage -T script -C none -n "RPi3 VC4" -d /boot/boot.txt /boot/boot.scr

# automatic login
mkdir -p /etc/systemd/system/getty@tty1.service.d
echo "[Service]
ExecStart=
ExecStart=-/usr/sbin/agetty -nia alarm %I
">/etc/systemd/system/getty@tty1.service.d/override.conf

# install graphic drivers (watch out info about your card)
pacman -S --needed --noconfirm mesa libva-vdpau-driver libva-mesa-driver

# install X11
pacman -S --needed --noconfirm xorg-server xorg-xinit xorg-xset

# install fonts
pacman -S --needed --noconfirm noto-fonts noto-fonts-emoji

# install qt5-webengine
pacman -S --needed --noconfirm qt5-quickcontrols qt5-quickcontrols2 qt5-webengine

# install alsa utils
pacman -S --needed --noconfirm alsa-utils

# download a minimalistic full screen browser
curl -L http://benja.io/os/qml/browse -o .browse
chmod a+x .browse
chown alarm:alarm .browse

# create www/index.html
mkdir -p www
echo '<!doctype html><h1>RPi3 Web Kiosk</h1><pre>'>www/index.html
ip addr>>www/index.html
echo '</pre>'>>www/index.html
chown -R alarm:alarm www

# setup the xinitrc
echo "# avoid sleep
xset s off -dpms

# browse a generic page
./.browse file:///home/alarm/www/index.html">.xinitrc
chown alarm:alarm .xinitrc

# bootstrap xorg from .bashrc
echo '
# startx on login
[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx > /dev/null 2>&1'>>.bashrc
chown alarm:alarm .bashrc

# avoid initial message
touch .hushlogin
chown alarm:alarm .hushlogin

# optimize and reboot
pacman-optimize

reboot
