#!/usr/bin/env bash

if [ "$(which sudo 2> /dev/null)" = "" ]; then
  bash <(curl -s https://archibold.io/utils/sudo)
else
  sudo pacman-key --init
  sudo pacman-key --populate archlinuxarm
  sudo pacman -Sy
fi

sudo groupadd weston-launch
sudo usermod -a -G wheel,games,power,optical,storage,scanner,lp,audio,video,weston-launch ${USER}

sudo mkdir -p /etc/systemd/system/getty@tty1.service.d
sudo sh -c "echo '[Service]
ExecStart=
ExecStart=-/usr/sbin/agetty -nia ${USER} %I
'>/etc/systemd/system/getty@tty1.service.d/override.conf"

source <(curl -s https://archibold.io/utils/aur)

aur --no-pgp cairo-glesv2-$(uname -m)
aur --no-pgp wpewebkit-gl-$(uname -m)

yes y | sudo pacman -Su --needed \
  gst-plugins-base gst-plugins-good gst-plugins-ugly gst-plugins-bad \
  gstreamer-vaapi gst-libav \
  geoip geoclue \
  weston mesa ttf-dejavu \
  wpebackend-fdo wayland-protocols \
  nodejs npm \
  unzip \
  gtk3

aur --no-pgp cog-wpe-gl

mkdir -p ~/.config
if [ ! -f ~/.config/weston.ini ]; then
  echo "[core]
idle-time=0
require-input=false

[shell]
client=${HOME}/.kiosk
animation=none
close-animation=none
startup-animation=none
locking=false

[output]
name=
mode=
">~/.config/weston.ini
fi

# Bash variables and bootstrap
if [ "$(cat ~/.bashrc | grep -F '[archibold.io] npm')" = "" ]; then
  mkdir -p ~/.npm-packages/bin
  npm config set prefix '~/.npm-packages'
  echo '
# [archibold.io] npm
export PATH="${PATH}:${HOME}/.npm-packages/bin"
export NODE_PATH="${NODE_PATH}:${HOME}/.npm-packages/lib/node_modules"
' >> ~/.bashrc
  export PATH="${PATH}:${HOME}/.npm-packages/bin"
  export NODE_PATH="${NODE_PATH}:${HOME}/.npm-packages/lib/node_modules"
fi

if [ "$(cat ~/.bashrc | grep -F '[archibold.io] weston')" = "" ]; then
  echo '
# [archibold.io] weston
export KIOSK_WIDTH=1280
export KIOSK_HEIGHT=720
export GTK_THEME="Adwaita:dark"

setWestonMode() {
  local MODE="$1"
  local NAME="$(ls /sys/class/drm | grep HDMI)"
  if [ "$NAME" != "" ]; then
    sed -i "s/name=.*/name=${NAME:6}/;s/mode=.*/mode=${MODE}/" ~/.config/weston.ini
  fi
}

if [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && [ "$(pgrep --list-name weston)" = "" ]; then
  setWestonMode "${KIOSK_WIDTH}x${KIOSK_HEIGHT}"
  if [ "$(which http-server)" = "" ]; then
    weston-launch
  else
    http-server ~/www/jellyfish & weston-launch
  fi
fi
'>>~/.bashrc
fi

if [ ! -d ~/www ]; then
  mkdir -p ~/www
  cd ~/www
  curl -LO https://archibold.io/demo/jellyfish.zip
  unzip jellyfish
  rm jellyfish.zip
fi

if [ ! -f ~/.kiosk ]; then
  npm i -g http-server
  echo '#!/usr/bin/env bash

HOST="127.0.0.1"
PAGE="http://${HOST}:8080/index.html"

# wait for http-server to be available
while true; do
  if [ "$(curl -s $PAGE)" != "" ]; then
    break
  else
    sleep 1
  fi
done

COG_PLATFORM_FDO_VIEW_WIDTH=$KIOSK_WIDTH COG_PLATFORM_FDO_VIEW_HEIGHT=$KIOSK_HEIGHT cog -P fdo $PAGE
'>~/.kiosk
  chmod a+x ~/.kiosk
fi
