#!/usr/bin/env bash

if [ "$(which sudo 2> /dev/null)" = "" ]; then
  bash <(curl -s https://archibold.io/utils/sudo)
else
  sudo pacman-key --init
  sudo pacman-key --populate archlinuxarm
  sudo pacman -Sy
fi

sudo groupadd weston-launch
sudo usermod -a -G wheel,games,power,optical,storage,scanner,lp,audio,video,weston-launch ${USER}

sudo mkdir -p /etc/systemd/system/getty@tty1.service.d
sudo sh -c "echo '[Service]
ExecStart=
ExecStart=-/usr/sbin/agetty -nia ${USER} %I
'>/etc/systemd/system/getty@tty1.service.d/override.conf"

if [ "$(cat ~/.bashrc | grep -F '[archibold.io] weston')" = "" ]; then
  echo '
# [archibold.io] weston
setWestonMode() {
  local MODE="$1"
  local NAME="$(ls /sys/class/drm | grep HDMI)"
  sed -i "s/name=.*/name=${NAME:6}/;s/mode=.*/mode=${MODE}/" ~/.config/weston.ini
}

if [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && [ "$(pgrep --list-name weston)" = "" ]; then
  setWestonMode "1280x720"
  weston-launch > /dev/null 2>&1
fi
'>>~/.bashrc
fi

source <(curl -s https://archibold.io/utils/aur)

aur --no-pgp cairo-glesv2-$(uname -m)
aur --no-pgp wpewebkit-gl-$(uname -m)

sudo pacman -Su --needed --noconfirm \
  gst-plugins-base gst-plugins-good gst-plugins-ugly gst-plugins-bad \
  gstreamer-vaapi gst-libav \
  geoip geoclue \
  weston mesa ttf-dejavu \
  wpebackend-fdo wayland-protocols \
  gtk3

aur --no-pgp cog-wpe-gl

if [ ! -f ~/.kiosk ]; then
  echo '#!/usr/bin/env sh
COG_PLATFORM_FDO_VIEW_FULLSCREEN=1 cog -P fdo https://akirodic.com/p/jellyfish/
'>~/.kiosk
  chmod a+x ~/.kiosk
fi

mkdir -p ~/.config
if [ ! -f ~/.config/weston.ini ]; then
  echo "[core]
idle-time=0
require-input=false

[shell]
client=${HOME}/.kiosk
animation=none
close-animation=none
startup-animation=none
locking=false

[output]
name=
mode=
">~/.config/weston.ini
fi
