#!/usr/bin/env bash

if [ "$(which sudo 2> /dev/null)" = "" ]; then
  echo -e "installing \x1B[1msudo\x1B[22m"
  echo root | su -c "
pacman-key --init
pacman-key --populate archlinuxarm
bash <(curl -s https://archibold.io/install/sudo)
"
  if [ "$(which sudo 2> /dev/null)" = "" ]; then
    echo -e "Unable to install \x1B[1msudo\x1B[22m"
    exit 1
  fi
else
  sudo pacman-key --init
  sudo pacman-key --populate archlinuxarm
fi

sudo usermod -a -G wheel,storage,power,video ${USER}

cd ~/

# avoid initial message
touch .hushlogin

# ArchLinux initialization + update
sudo pacman -Sy
while ! sudo pacman -Su --needed --noconfirm \
  dhcpcd openssh cpupower \
  ttf-dejavu noto-fonts noto-fonts-emoji noto-fonts-extra \
  iptables dialog wpa_supplicant openssh libnotify \
  base-devel git diffstat chrpath wget cpio pv \
  gnome-themes-extra adwaita-icon-theme \
  gst-plugins-base gst-plugins-good gst-plugins-ugly gst-libav \
  libva-vdpau-driver libva-mesa-driver \
  gconf nss pulseaudio pulseaudio-alsa gperf libexif \
  alsa-utils libcanberra-gstreamer libcanberra-pulse \
  gstreamer-vaapi \
  geoip geoip-database-extra geoclue
do
  :
done

# default locale
sudo sh -c "echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen"
sudo sh -c "echo 'LOCALE=en_US.UTF-8'>>/etc/locale.conf"
sudo sh -c "echo 'LANG=en_US.UTF-8'>>/etc/locale.conf"
sudo sh -c "echo 'LC_TIME=en_US.UTF-8'>>/etc/locale.conf"
sudo sh -c "localectl set-locale LANG=en_US.UTF-8"
sudo locale-gen
sudo sh -c 'locale > /etc/locale.conf'

# terminal welcome logo
if [ "$BENJA_LOGO" = "" ]; then
  echo "adding terminal welcome logo"
  curl -LOs https://archibold.io/benja/logo
  mv logo .logo
  sleep 1
fi

if [ "$GTK_THEME" = "" ]; then
  echo "using Adwaita:dark theme"
  export GTK_THEME="Adwaita:dark"
  echo "GTK_THEME='${GTK_THEME}'">>.bashrc
  sleep 1
fi

# automatic login
sudo mkdir -p /etc/systemd/system/getty@tty1.service.d
sudo sh -c "echo '[Service]
ExecStart=
ExecStart=-/usr/sbin/agetty -nia ${USER} %I
'>/etc/systemd/system/getty@tty1.service.d/override.conf"

# setup app folder
if [ ! -f /etc/systemd/system/app-disk.service ]; then
  echo "setting ~/app folder"
  mkdir -p ${HOME}/app
  echo "[Unit]
Description=app ${HOME}/app disk

[Service]
User=root
Type=simple
ExecStart=/usr/bin/mount /dev/mmcblk0p3 ${HOME}/app -o uid=${USER},gid=users,umask=0022

[Install]
WantedBy=multi-user.target
">${HOME}/app/app-disk.service
  echo "#!/usr/bin/env bash
mv ${HOME}/app/app-disk.service /etc/systemd/system/app-disk.service
systemctl enable app-disk.service
systemctl start app-disk.service
rm ${HOME}/app/bash
">${HOME}/app/bash
  sync
  sudo bash ${HOME}/app/bash
  sleep 1
fi

# configure 80 to 8080 redirect
if [ ! -f /etc/systemd/system/redirect80to8080.service ]; then
  echo "setting port 80 to 8080 redirects"
  echo "[Unit]
Description=Redirect 80 to 8080 service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
ExecStart=/usr/bin/iptables -t nat -I OUTPUT -p tcp -o lo --dport 80 -j REDIRECT --to-port 8080

[Install]
WantedBy=multi-user.target
" >redirect80to8080.service
  sudo mv redirect80to8080.service /etc/systemd/system/
  sudo systemctl enable redirect80to8080.service
  sleep 1
fi

# configure rmate
if [ ! -f /usr/bin/rmate ]; then
  echo "adding rmate"
  curl -LOs 'https://raw.githubusercontent.com/WebReflection/rmate/master/rmate'
  chmod a+x rmate
  sudo mv rmate /usr/bin/rmate
  sleep 1
fi

# configure hostname
if [ ! -f /etc/hostname ] || [ "$(cat /etc/hostname | grep ${USER}.local)" = "" ]; then
  echo "configuring hostname"
  if [ -f /etc/hostname ]; then
    cat /etc/hostname > hostname
  fi
  echo "${USER}.local" >> hostname
  sudo mv hostname /etc/
  sudo hostnamectl set-hostname "${USER}.local"
  sudo sed -i "s/localhost\$/localhost$(printf '\t')${USER}.local/g" /etc/hosts
  sleep 1
fi

# attempt to avoid suspend mode when on terminal
if [ "$(cat /etc/systemd/logind.conf | grep 'HandleSuspendKey=ignore')" = "" ]; then
  echo "ignoring suspend on terminal"
  sudo sh -c 'echo "HandleSuspendKey=ignore">>/etc/systemd/logind.conf'
  sudo sh -c 'echo "HandleLidSwitch=ignore">>/etc/systemd/logind.conf'
  sleep 1
fi

if [ "$(which echomd 2> /dev/null)" = "" ]; then
  echo "installing echomd"
  bash <(curl -s https://archibold.io/install/echomd)
fi
