#!/usr/bin/env bash

while ! sudo pacman -S --needed --noconfirm \
  xorg-server xorg-xinit xorg-xset xorg-xrandr xorg-server-xwayland \
  xterm unclutter \
  alsa-utils libcanberra-gstreamer libcanberra-pulse \
  gst-plugins-base gst-plugins-good \
  gstreamer-vaapi \
  gst-libav gst-plugins-ugly \
  geoip geoclue
do
  :
done

# Xorg / xinit conifg
curl -LO https://archibold.io/benja/setup/benja_xinitrc
mv benja_xinitrc .xinitrc
