#!/usr/bin/env bash

if [ ! -f ~/app/package.json ]; then
  echo ' installing app'
  cd ~/app
  curl -LOs "https://archibold.io/benja/app/index.js"
  curl -LOs "https://archibold.io/benja/app/index.html"
  curl -LOs "https://archibold.io/benja/app/package.json"
  curl -LOs "https://archibold.io/benja/app/logo-dark.svg"
  curl -LOs "https://archibold.io/benja/app/logo-light.svg"
  touch reload
  mkdir -p node_modules
  npm install --production --no-bin-links
  cd -
  sleep 1
fi
