#!/usr/bin/env bash

while ! sudo pacman -S --needed --noconfirm npm nodejs
do
  :
done

sudo pacman -Sc --noconfirm
mkdir -p ~/.npm-packages/bin
npm config set prefix '~/.npm-packages'
npm config set package-lock false

# configure npm and sudo
if [ "$(sudo cat /etc/sudoers | grep /usr/bin/npm)" = "" ]; then
  sudo sh -c "echo '
# sudo npm
${USER} ALL=NOPASSWD: /usr/bin/npm
'>>/etc/sudoers"
fi

export PATH="${PATH}:${HOME}/.npm-packages/bin"
export NODE_PATH="${NODE_PATH}:${HOME}/.npm-packages/lib/node_modules"

echo "
# npm and nodejs global modules
export PATH=\"$PATH\"
export NODE_PATH=\"$NODE_PATH\"
" >> ~/.bashrc
