#!/usr/bin/env bash

sudo pacman -S --needed --noconfirm \
  npm nodejs \
  c-ares ffmpeg gtk3 http-parser libevent libnghttp2 libxslt libxss minizip nss re2 snappy

mkdir -p ~/.npm-packages/bin
npm config set prefix '~/.npm-packages'
npm config set package-lock false

# configure npm and sudo
if [ "$(cat /etc/sudoers | grep /usr/bin/npm)" = "" ]; then
  sudo sh -c "echo '
# sudo npm
${USER} ALL=NOPASSWD: /usr/bin/npm
'>>/etc/sudoers"
fi

echo '
# npm and nodejs global modules
export PATH="$PATH:$HOME/.npm-packages/bin"
export NODE_PATH="$NODE_PATH:$HOME/.npm-packages/lib/node_modules"
' >> ~/.bashrc

export PATH="$PATH:$HOME/.npm-packages/bin"
export NODE_PATH="$NODE_PATH:$HOME/.npm-packages/lib/node_modules"

npm i -g electron johnny-five
