#!/usr/bin/env bash

echo "
Please choose your wifi and write its password when/if asked.
Please ignore possible info coming up during this process.
"
sleep 3
echo root | su -c "wifi-menu"
echo "
trying to configure the wifi automatically
"
WLAN=$(netctl list)
if [ "$WLAN" != "" ]; then
  echo root | su -c "netctl enable ${WLAN:2}"
  echo "wifi ${WLAN:2} enabled"
  echo ""
  echo "please wait until shutdown"
  echo "then switch it on again and login"
  echo ""
  sleep 3
  echo root | su -c "systemctl enable dhcpcd"
  echo root | su -c "systemctl restart dhcpcd"
  echo root | su -c "systemctl daemon-reload"
  echo root | su -c 'echo "static domain_name_servers=208.67.222.222 208.67.220.220">>/etc/resolvconf.conf'
  echo root | su -c "shutdown -h now"
else
  echo "unable to configure the wifi"
  exit 1
fi
