#!/usr/bin/env bash

while ! sudo pacman -S --needed --noconfirm \
  xorg-server xorg-xinit xorg-xset xorg-xrandr xorg-server-xwayland \
  xterm unclutter
do
  :
done

# Xorg / xinit conifg
curl -LO https://archibold.io/benja/setup/benja_xinitrc
mv benja_xinitrc .xinitrc
