#!/usr/bin/env bash

sudo pacman -S --needed --noconfirm npm nodejs

mkdir -p ~/.npm-packages/bin
npm config set prefix '~/.npm-packages'

echo '
# npm and nodejs global modules
export PATH="$PATH:$HOME/.npm-packages/bin"
export NODE_PATH="$NODE_PATH:$HOME/.npm-packages/lib/node_modules"
' >> ~/.bashrc

export PATH="$PATH:$HOME/.npm-packages/bin"
export NODE_PATH="$NODE_PATH:$HOME/.npm-packages/lib/node_modules"

npm i -g electron
