#!/usr/bin/env bash

if [ -f /boot/boot.txt ] && [ ! -f ./boot.txt.bck ]; then
  cp /boot/boot.txt ./boot.txt.bck
fi

if [ -f /boot/cmdline.txt ] && [ ! -f ./cmdline.txt.bck ]; then
  cp /boot/cmdline.txt ./cmdline.txt.bck
fi

cd ~/
git clone https://github.com/waveshare/LCD-show.git
cd LCD-show/
chmod +x LCD35-show
./LCD35-show

# echo 'Section "Device"
#   Identifier "Benja IO SPI FBDEV"
#   Driver "fbdev"
#   Option "fbdev" "/dev/fb1"
#   Option "SwapbuffersWait" "true"
# EndSection' > ./99-fbdev.conf
# sudo mv ./99-fbdev.conf /usr/share/X11/xorg.conf.d/99-fbdev.conf

# echo 'Section "InputClass"
#   Identifier "calibration"
#   MatchProduct "ADS7846 Touchscreen"
#   Option "Calibration" "3932 300 294 3801"
#   Option "SwapAxes" "1"
# EndSection' > ./99-calibration.conf
# sudo mv ./99-calibration.conf /etc/X11/xorg.conf.d/99-calibration.conf

# if [ ! -f /boot/overlays/waveshare35a.dtbo ]; then
#   curl -LO https://archibold.io/benja/bin/waveshare35a.dtbo
#   sudo mkdir -p /boot/overlays
#   sudo mv waveshare35a.dtbo /boot/overlays/waveshare35a.dtbo
# fi

# sudo sh -c 'echo "
# dtoverlay=ads7846,penirq=25,penirq_pull=2,xohms=150,swapxy=1,xmin=300,ymin=700,xmax=3800,ymax=3400,pmax=255
# dtoverlay=waveshare35a
# ">>/boot/config.txt'

# if [ -f /boot/boot.txt ]; then
#   sudo sed -i "s/rootwait/dwc_otg.lpm_enable=0 rootwait fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo/" /boot/boot.txt
#   sudo mkimage -T script -C none -n "Raspberry Pi" -d /boot/boot.txt /boot/boot.scr
# fi

# if [ -f /boot/cmdline.txt ]; then
#   echo "dwc_otg.lpm_enable=0 $(cat /boot/cmdline.txt) fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo" > ./cmdline.txt
#   sudo mv ./cmdline.txt /boot/cmdline.txt
# fi
