#!/usr/bin/env bash

echo 'Section "Device"
  Identifier "Benja IO SPI FBDEV"
  Driver "fbdev"
  Option "fbdev" "/dev/fb1"
  Option "SwapbuffersWait" "true"
EndSection' > ./99-fbdev.conf
sudo mv ./99-fbdev.conf /usr/share/X11/xorg.conf.d/99-fbdev.conf

echo 'Section "InputClass"
  Identifier "calibration"
  MatchProduct "ADS7846 Touchscreen"
  Option "Calibration" "3932 300 294 3801"
  Option "SwapAxes" "1"
EndSection' > ./99-calibration.conf
sudo mv ./99-calibration.conf /etc/X11/xorg.conf.d/99-calibration.conf

if [ ! -f /boot/overlays/waveshare35a.dtbo ]; then
  curl -LO https://archibold.io/benja/bin/waveshare35a.dtbo
  sudo mv waveshare35a.dtbo /boot/overlays/waveshare35a.dtbo
fi

cp /boot/config.txt ./config.txt
echo '
dtparam=audio=on
dtparam=spi=on
dtoverlay=ads7846,penirq=25,penirq_pull=2,xohms=150,swapxy=1,xmin=300,ymin=700,xmax=3800,ymax=3400,pmax=255
dtoverlay=waveshare35a' >> config.txt
sudo mv ./config.txt /boot/config.txt

if [ -f /boot/boot.txt ]; then
  echo "dwc_otg.lpm_enable=0 $(cat /boot/boot.txt) fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo" > ./boot.txt
  sudo mv ./boot.txt /boot/boot.txt
  sudo mkimage -T script -C none -n "Raspberry Pi" -d /boot/boot.txt /boot/boot.scr
fi

if [ -f /boot/cmdline.txt ]; then
  echo "dwc_otg.lpm_enable=0 $(cat /boot/cmdline.txt) fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo" > ./cmdline.txt
  sudo mv ./cmdline.txt /boot/cmdline.txt
fi
