#!/usr/bin/env bash

if [ "$(which sudo 2> /dev/null)" = "" ]; then
  echo -e "Installing \x1B[1msudo\x1B[22m"
  echo "root" | su -c "
pacman-key --init
pacman-key --populate archlinuxarm
bash <(curl -s https://archibold.io/install/sudo)
"

  if [ "$(which sudo 2> /dev/null)" = "" ]; then
    echo -e "Unable to install \x1B[1msudo\x1B[22m"
    exit 1
  fi
else
  sudo pacman-key --init
  sudo pacman-key --populate archlinuxarm
fi

# first thing: update the time or HTTPS won't work
if [ "$(which ntpdate 2> /dev/null)" != "" ]; then
  sudo ntpdate pool.ntp.org
  sudo timedatectl set-local-rtc 1
fi

sudo usermod -a -G video ${USER}

bash <(curl -s https://archibold.io/benja/setup/_common)
bash <(curl -s https://archibold.io/benja/setup/_xorg)
bash <(curl -s https://archibold.io/benja/setup/_npm)

echo "dtoverlay=vc4-fkms-v3d

gpu_mem=128
gpu_mem_256=128
gpu_mem_512=196
gpu_mem_1024=384

dtparam=audio=on
dtparam=spi=on

[all]
avoid_warnings=1
disable_splash=1
boot_delay=0
">config.txt

sudo mv config.txt /boot/ 2> /dev/null

if [ -f /boot/boot.txt ]; then
  # modify boot.scr to reserve cma memory and make the boot silent
  while ! sudo pacman -S --needed --noconfirm uboot-tools
  do
    :
  done
  sudo sed -i "s/rootwait/rootwait quiet loglevel=0 cma=384MB@128MB/" /boot/boot.txt
  # sed -i "s/rootwait/rootwait cma=384MB@128MB/" /boot/boot.txt
  sudo mkimage -T script -C none -n "RPi3 VC4" -d /boot/boot.txt /boot/boot.scr
fi

if [ -f /boot/cmdline.txt ]; then
  # modify cmdline.txt mostly to make the boot silent (cma might be ignored)
  sudo sed -i "s/rootwait/rootwait quiet loglevel=0 cma=384MB@128MB/" /boot/cmdline.txt
fi

# install specific GPU / Xorg driver
while ! sudo pacman -S --needed --noconfirm \
  mesa libva-vdpau-driver libva-mesa-driver xf86-video-fbdev mesa-vdpau
do
  :
done

# startx on login
echo '
# startx on login
[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx > /dev/null 2>&1'>>.bashrc
