#!/usr/bin/env bash

bash <(curl -s https://archibold.io/benja/setup/benja_common)

# install specific GPU / Xorg driver
while ! sudo pacman -S --needed --noconfirm \
  mesa libva-vdpau-driver libva-mesa-driver xf86-video-fbdev mesa-vdpau
do
  :
done

sudo pacman -Sc --noconfirm

bash <(curl -s https://archibold.io/benja/setup/benja_autologin)
bash <(curl -s https://archibold.io/benja/setup/benja_xorg)
bash <(curl -s https://archibold.io/benja/setup/rpi_quiet)
bash <(curl -s https://archibold.io/benja/setup/benja_electron)

echo '
# startx on login
if [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  exec startx > /dev/null 2>&1
else
  source .logo
  echomd "$BENJA_LOGO"
fi
'>>.bashrc

bash <(curl -s https://archibold.io/benja/setup/rpi_config)
bash <(curl -s https://archibold.io/benja/setup/rpi_raspi-io)
bash <(curl -s https://archibold.io/benja/setup/benja_app)
bash <(curl -s https://archibold.io/benja/setup/benja_z)
