#!/usr/bin/env bash

aur python-pigpio-git
cd ~/
if [ ! -f package.json ]; then
  echo '{"private":true}' > package.json
fi
mkdir -p node_modules
npm i --save raspi-io johnny-five
cd -
sudo ln -s /usr/local/lib/libpigpio* /usr/lib/
