#!/usr/bin/env bash

bash <(curl -s https://archibold.io/benja/setup/benja_common)

# install specific GPU / Xorg driver
while ! sudo pacman -S --needed --noconfirm \
  mesa libva-vdpau-driver libva-mesa-driver xf86-video-fbdev mesa-vdpau
do
  :
done

bash <(curl -s https://archibold.io/benja/setup/benja_xorg)
bash <(curl -s https://archibold.io/benja/setup/benja_autologin)
bash <(curl -s https://archibold.io/benja/setup/rpi_quiet)
bash <(curl -s https://archibold.io/benja/setup/benja_electron)

echo '
# startx on login
if [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  exec startx > /dev/null 2>&1
else
  source .logo
  echomd "$BENJA_LOGO"
fi
'>>.bashrc

echo "dtoverlay=vc4-fkms-v3d,cma-384

gpu_mem=128
gpu_mem_256=128
gpu_mem_512=196
gpu_mem_1024=384

dtparam=audio=on
dtparam=spi=on

[all]
avoid_warnings=1
disable_splash=1
boot_delay=0
">config.txt

sudo mv config.txt /boot/ 2> /dev/null

# raspi-io
echo -e "root
root" | aur python-pigpio-git
npm i -g raspi-io
sudo ln -s /usr/local/lib/libpigpio*.so /usr/lib/

bash <(curl -s https://archibold.io/benja/setup/benja_app)
bash <(curl -s https://archibold.io/benja/setup/benja_z)
