#!/usr/bin/env bash

bash <(curl -s https://archibold.io/benja/setup/benja_common)
bash <(curl -s https://archibold.io/benja/setup/benja_npm)

# install specific GPU / Xorg driver
while ! sudo pacman -S --needed --noconfirm \
  mesa libva-vdpau-driver libva-mesa-driver xf86-video-fbdev mesa-vdpau
do
  :
done

# use startx to autologin and start the session
bash <(curl -s https://archibold.io/benja/setup/benja_xorg)
bash <(curl -s https://archibold.io/benja/setup/benja_autologin)
echo '
# startx on login
if [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  exec startx > /dev/null 2>&1
else
  source .logo
  echomd "$BENJA_LOGO"
fi
'>>.bashrc

echo "dtoverlay=vc4-fkms-v3d,cma-384

gpu_mem=128
gpu_mem_256=128
gpu_mem_512=196
gpu_mem_1024=384

dtparam=audio=on
dtparam=spi=on

[all]
avoid_warnings=1
disable_splash=1
boot_delay=0
">config.txt

sudo mv config.txt /boot/ 2> /dev/null

if [ -f /boot/boot.txt ]; then
  # modify boot.scr to reserve cma memory and make the boot silent
  while ! sudo pacman -S --needed --noconfirm uboot-tools
  do
    :
  done
  sudo sed -i "s/rootwait/rootwait quiet loglevel=0 cma=384MB@128MB/" /boot/boot.txt
  # sed -i "s/rootwait/rootwait cma=384MB@128MB/" /boot/boot.txt
  sudo mkimage -T script -C none -n "Raspberry Pi" -d /boot/boot.txt /boot/boot.scr
fi

if [ -f /boot/cmdline.txt ]; then
  # modify cmdline.txt mostly to make the boot silent (cma might be ignored)
  sudo sed -i "s/rootwait/rootwait quiet loglevel=0 cma=384MB@128MB/" /boot/cmdline.txt
fi

# raspi-io
echo -e "root
root" | aur python-pigpio-git
npm i -g raspi-io
sudo ln -s /usr/local/lib/libpigpio*.so /usr/lib/

bash <(curl -s https://archibold.io/benja/setup/benja_app)
bash <(curl -s https://archibold.io/benja/setup/benja_z)
