#!/usr/bin/env bash

if [ "$(pacman -Qs linux-rpi)" = "" ]; then
  clear
  echo ""
  echo "Would you like to use linux-rpi kernel? [y/N]"
  echo "Use this option if you had GPU issues before"
  echo ""
  read -n1 -s RPi4
  if [ "$RPi4" = "y" ] || [ "$RPi4" = "Y" ]; then
    bash <(curl -s https://archibold.io/install/linux-rpi)
  fi
fi
