#!/usr/bin/env bash

bash <(curl -s https://archibold.io/kiosk/wpe-base)
bash <(curl -s https://archibold.io/install/pi-config)

echo ""
echo "Reboot in 3 seconds ..."
sleep 1
echo "Reboot in 2 seconds ..."
sleep 1
echo "Reboot in 1 second ..."
sleep 1
echo "Rebooting"
echo ""

sudo reboot
