#!/usr/bin/env bash

arch="$(uname -m)"
if [ "$arch" = "armv7h" ]; then
    arch="armv7l"
fi

if [ "$(whoami)" = "root" ]; then
    echo 'you cannot be root to make a package'
    exit 1
fi

sudo pacman -Sy

# dependencies
sudo pacman -S --needed --noconfirm libpng libxrender libxext fontconfig pixman glib2 lzo mesa

# make dependencies
sudo pacman -S --needed --noconfirm base-devel librsvg poppler-glib libspectre valgrind git

getHash() {
    for hash in $("${1}sum" $2); do
        echo $hash
        return
    done
}

addLicense() {
    mkdir -p ~/aur/builds/${pkgname}/usr/share/licenses/cairo/
    cp ~/git/cairo/COPYING* ~/aur/builds/${pkgname}/usr/share/licenses/cairo/
}

mkdir -p ~/git
cd ~/git

if [ ! -d cairo ]; then
    yes yes | git clone https://gitlab.freedesktop.org/cairo/cairo.git
fi
cd cairo

git add .
git reset --hard
git pull --rebase

NOCONFIGURE=1 ./autogen.sh

./configure --prefix=/usr \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --disable-static \
        --disable-gl \
        --enable-egl \
        --enable-glesv2 \
        --enable-xlib-xcb \
        --enable-tee \
        --enable-svg \
        --enable-ps \
        --enable-pdf \
        --enable-gobject \
        --disable-gtk-doc \
        --enable-full-testing \
        --enable-test-surfaces

sed -i 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool

if [[ ! $? -eq 0 ]]; then
    echo 'unable to configure'
    exit $?
fi

make

if [[ ! $? -eq 0 ]]; then
    echo 'unable to make'
    exit $?
fi

pkgname="cairo-glesv2-bin"
pkgver="$(git describe --tags | sed 's/-.*//g')"
pkgtar="$pkgname-$arch-$pkgver.tar.gz"

rm -rf ~/aur/builds/$pkgname
mkdir -p ~/aur/builds/$pkgname

make DESTDIR=~/aur/builds/$pkgname install

addLicense

mkdir -p ~/git/
cd ~/git
if [ ! -d aur ]; then
    yes yes | git clone git@github.com:WebReflection/aur.git
fi

cd ~/git/aur/

git add .
git reset --hard
git pull --rebase

rm -rf $pkgtar
mv ~/aur/builds/$pkgname/usr ./
tar -czf $pkgtar usr
rm -rf usr

mkdir -p $pkgname
cd $pkgname

echo "# Maintainer: Andrea Giammarchi <andrea.giammarchi@gmail.com>
pkgname=$pkgname
pkgver=$pkgver
arch=(aarch64 armv7h armv7l x86_64)
pkgrel=1
pkgdesc='Cairo vector graphics library (glesv2 version)'
url='http://cairographics.org/'
license=('LGPL' 'MPL')
provides=('cairo=$pkgver' 'cairo-gl=$pkgver' 'cairo-xcb=$pkgver')
conflicts=('cairo' 'cairo-gl' 'cairo-xcb')
depends=('libpng' 'libxrender' 'libxext' 'fontconfig' 'pixman>=0.28.0' 'glib2' 'mesa' 'libgl' 'lzo')
source_aarch64=('${pkgname}-aarch64::https://webreflection.github.io/aur/${pkgname}-aarch64-${pkgver}.tar.gz')
source_armv7h=('${pkgname}-armv7h::https://webreflection.github.io/aur/${pkgname}-armv7l-${pkgver}.tar.gz')
source_armv7l=('${pkgname}-armv7l::https://webreflection.github.io/aur/${pkgname}-armv7l-${pkgver}.tar.gz')
source_x86_64=('${pkgname}-x86::https://webreflection.github.io/aur/${pkgname}-x86_64-${pkgver}.tar.gz')
">TEMPLATE

cd ~/git/aur/
git add .
git commit -m "Pushing ${pkgname}-${pkgver}"
git push

echo ""
echo "$(tput bold)$pkgname$(tput sgr0) successfully uploaded"
echo ""
