#!/usr/bin/env bash

if [ "$(whoami)" = "root" ]; then
    echo 'you cannot be root to make a package'
    exit 1
fi

for info in $(pacman -Ss webkit2gtk | sed -E 's/^.*webkit2gtk ([^ ]*).*/\1/'); do
    pkgver=$(echo $info | sed -E 's/^([^-]*).*$/\1/')
    pkgrel=$(echo $info | sed -E 's/^[^-]*-(.*)$/\1/')
    break
done

if [ "$pkgver" = "" ] || [ "$pkgrel" = "" ]; then
    pacman -Ss webkit2gtk
    echo 'unable to retrieve the version'
    exit 1
fi

pkgname="webkit2gtk-wpe-bin"

arch="$(uname -m)"
if [ "$arch" = "armv7h" ]; then
    arch="armv7l"
fi

pkgtar="$pkgname-$arch-$pkgver.tar.gz"

addLicense() {
    local _f
    cd ~/aur/$pkgname/webkitgtk-${pkgver}
    mkdir -p ~/aur/builds/$pkgname/usr/share/licenses/${pkgname}/
    while IFS= read -d $'\0' -r _f ; do
        echo "### ${_f} ###" ; cat "${_f}" ; echo
    done < <(find Source -name COPYING -or -name 'LICENSE*' -print0 | sort -zu) > ~/aur/builds/$pkgname/usr/share/licenses/${pkgname}/LICENSE
}

echo "Building $pkgname-$arch-$pkgver"
sleep 2

sudo pacman -Sy

# dependencies
sudo pacman -S --needed --noconfirm libxt libxslt enchant gst-plugins-base-libs libsecret libwebp openjpeg2 \
                                    harfbuzz-icu gtk3 libnotify hyphen woff2 libwpe wpebackend-fdo bubblewrap \
                                    xdg-dbus-proxy libmanette

# make dependencies
sudo pacman -S --needed --noconfirm base-devel gperf ruby cmake python ninja gtk-doc \
                                    gperf gobject-introspection ruby gtk-doc cmake python geoclue gst-plugins-bad

sudo pacman -S --needed --noconfirm libxslt gst-plugins-base-libs libepoxy libsoup libwebp \
    harfbuzz-icu woff2 openjpeg2 libseccomp bubblewrap xdg-dbus-proxy \
    geoclue at-spi2-atk libwpe hyphen \
    qt5-quickcontrols2

sudo pacman -S --needed --noconfirm gst-plugin-wpe

mkdir -p ~/aur/$pkgname
cd ~/aur/$pkgname

if [ ! -f webkitgtk-${pkgver}.tar.xz ]; then
    curl -LO https://webkitgtk.org/releases/webkitgtk-${pkgver}.tar.xz
    tar -xf webkitgtk-${pkgver}.tar.xz
fi

if [ ! -d webkitgtk-${pkgver} ]; then
    echo 'unable to find the directory'
    exit 1
fi

cmake -H"webkitgtk-${pkgver}" -Bbuild       \
        -DCMAKE_BUILD_TYPE=Release          \
        -DCMAKE_INSTALL_PREFIX=/usr         \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib     \
        -DCMAKE_SKIP_RPATH=ON               \
        -DPYTHON_EXECUTABLE=/usr/bin/python \
        -DENABLE_GTKDOC=ON                  \
        -DENABLE_ACCELERATED_2D_CANVAS=ON   \
        -DENABLE_ENCRYPTED_MEDIA=ON         \
        -DENABLE_WPE_QT_API=OFF             \
        -DPORT=GTK                          \
        -DLIB_INSTALL_DIR=/usr/lib          \
        -DUSE_WOFF2=ON                      \
        -DUSE_WPE_RENDERER=ON               \
        -DENABLE_BUBBLEWRAP_SANDBOX=OFF     \
        -GNinja

cmake --build build

if [[ ! $? -eq 0 ]]; then
    echo 'unable to build'
    exit $?
fi

rm -rf ~/aur/builds/$pkgname
mkdir -p ~/aur/builds/$pkgname

DESTDIR=~/aur/builds/$pkgname cmake --build build --target install

addLicense

mkdir -p ~/git/
cd ~/git
if [ ! -d aur ]; then
    yes yes | git clone git@github.com:WebReflection/aur.git
fi

cd ~/git/aur/

git add .
git reset --hard
git pull --rebase

rm -rf $pkgtar
mv ~/aur/builds/$pkgname/usr ./
tar -czf $pkgtar usr
rm -rf usr

mkdir -p $pkgname
cd $pkgname

echo "# Maintainer: Andrea Giammarchi <andrea.giammarchi@gmail.com>
pkgname=$pkgname
pkgver=$pkgver
pkgrel=$pkgrel
arch=(aarch64 armv7h armv7l x86_64)
pkgdesc='GTK+ Web content engine library (WPE version)'
url='https://webkitgtk.org'
license=(custom)
provides=('webkit2gtk' 'webkit2gtk-git')
conflicts=('webkit2gtk' 'webkit2gtk-git')
depends=(cairo fontconfig freetype2 glib2 harfbuzz harfbuzz-icu icu libjpeg
         libepoxy libgcrypt libsoup libxml2 zlib libpng sqlite libwebp
         atk at-spi2-core openjpeg2 woff2 libtasn1 libxslt libsystemd bubblewrap
         libegl libgl libgles libwpe libx11 libxext libice libxt
         libseccomp xdg-dbus-proxy gstreamer gst-plugins-base-libs libxkbcommon
         wayland wpebackend-fdo hyphen libnotify gtk3 libsecret gst-plugin-wpe
         enchant libmanette)
optdepends=('geoclue: Geolocation support'
            'gst-plugins-good: media decoding'
            'gst-plugins-bad: media decoding'
            'gst-libav: nonfree media decoding')
source_aarch64=('${pkgname}-aarch64::https://webreflection.github.io/aur/${pkgname}-aarch64-${pkgver}.tar.gz')
source_armv7h=('${pkgname}-armv7h::https://webreflection.github.io/aur/${pkgname}-armv7l-${pkgver}.tar.gz')
source_armv7l=('${pkgname}-armv7l::https://webreflection.github.io/aur/${pkgname}-armv7l-${pkgver}.tar.gz')
source_x86_64=('${pkgname}-x86::https://webreflection.github.io/aur/${pkgname}-x86_64-${pkgver}.tar.gz')
">TEMPLATE

cd ~/git/aur/
git add .
git commit -m "Pushing ${pkgname}-${pkgver}"
git push

echo ""
echo "$(tput bold)$pkgname$(tput sgr0) successfully uploaded"
echo ""
