#!/usr/bin/env bash

if [ "$(whoami)" = "root" ]; then
    echo 'you cannot be root to make a package'
    exit 1
fi

sudo pacman -Sy

# dependencies
sudo pacman -S --needed --noconfirm libpng libxrender libxext fontconfig pixman glib2 lzo mesa

# make dependencies
sudo pacman -S --needed --noconfirm base-devel librsvg poppler-glib libspectre valgrind git

getHash() {
    for hash in $("${1}sum" $2); do
        echo $hash
        return
    done
}

addLicense() {
    mkdir -p ~/aur/builds/${pkgname}/usr/share/licenses/cairo/
    cp ~/git/cairo/COPYING* ~/aur/builds/${pkgname}/usr/share/licenses/cairo/
}

mkdir -p ~/git
cd ~/git

if [ ! -d cairo ]; then
    yes yes | git clone https://gitlab.freedesktop.org/cairo/cairo.git
fi
cd cairo

git add .
git reset --hard
git pull --rebase

NOCONFIGURE=1 ./autogen.sh

./configure --prefix=/usr \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --disable-static \
        --disable-gl \
        --enable-egl \
        --enable-glesv3 \
        --enable-xlib-xcb \
        --enable-tee \
        --enable-svg \
        --enable-ps \
        --enable-pdf \
        --enable-gobject \
        --disable-gtk-doc \
        --enable-full-testing \
        --enable-test-surfaces

sed -i 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool

if [[ ! $? -eq 0 ]]; then
    echo 'unable to configure'
    exit $?
fi

make

if [[ ! $? -eq 0 ]]; then
    echo 'unable to make'
    exit $?
fi

arch="$(uname -m)"
pkgname="cairo-glesv3-$arch"
pkgver="$(git describe --tags | sed 's/-.*//g')"
pkgtar="$pkgname-$pkgver.tar.gz"

rm -rf ~/aur/builds/$pkgname
mkdir -p ~/aur/builds/$pkgname

make DESTDIR=~/aur/builds/$pkgname install

addLicense

mkdir -p ~/git/
cd ~/git
if [ ! -d aur ]; then
    yes yes | git clone git@github.com:WebReflection/aur.git
fi

cd ~/git/aur/

git add .
git reset --hard
git pull --rebase

rm -rf $pkgtar
mv ~/aur/builds/$pkgname/usr ./
tar -czf $pkgtar usr
rm -rf usr

mkdir -p $pkgname
cd $pkgname

if [ "$arch" != "aarch64" ]; then
    arch="armv7l armv7h"
fi

echo "# Maintainer: Andrea Giammarchi <andrea.giammarchi@gmail.com>
pkgname=$pkgname
pkgver=$pkgver
arch=($arch)
pkgrel=1
pkgdesc='Cairo vector graphics library (glesv3 version)'
url='http://cairographics.org/'
license=('LGPL' 'MPL')
provides=('cairo=$pkgver' 'cairo-gl=$pkgver' 'cairo-xcb=$pkgver')
conflicts=('cairo' 'cairo-gl' 'cairo-xcb')
depends=('libpng' 'libxrender' 'libxext' 'fontconfig' 'pixman>=0.28.0' 'glib2' 'mesa' 'libgl' 'lzo')
source=('https://webreflection.github.io/aur/$pkgtar')
md5sums=('$(getHash md5 ~/git/aur/$pkgtar)')
sha1sums=('$(getHash sha1 ~/git/aur/$pkgtar)')
sha256sums=('$(getHash sha256 ~/git/aur/$pkgtar)')
sha512sums=('$(getHash sha512 ~/git/aur/$pkgtar)')
">PKGBUILD

echo 'package () {
    cp -R "${srcdir}/usr" "${pkgdir}"
}'>>PKGBUILD

makepkg --printsrcinfo > .SRCINFO

cd ~/git/aur/
git add .
git commit -m "Pushing ${pkgname}-${pkgver}"
git push

echo ""
echo "$(tput bold)$pkgname$(tput sgr0) successfully uploaded"
echo ""
