#!/usr/bin/env bash

#########################
# archibold.io (C) 2016 #
#########################

if [ "$(which sudo 2> /dev/null)" = "" ]; then
  bash <(curl -s archibold.io/install/sudo)
fi

archibold() {
  local TMP=
  case $1 in

    clean)
      sudo pacman -Sc --noconfirm
      sudo pacman-optimize
      ;;

    reset-keys)
      sudo dirmngr </dev/null
      sudo pacman -Sy --noconfirm
      sudo pacman-key -u
      sudo pacman-key --populate archlinux
      sudo pacman-key --refresh-keys
      ;;

    update)
      if [ "$(which archibold 2> /dev/null)" != "" ]; then
        TMP="$(which archibold)"
        cd /tmp
        curl -LO archibold.io/utils/archibold
        echo 'archibold "$@"' >> archibold
        chmod a+x archibold
        sudo mv archibold $TMP
      fi
      if [ "$(which yaourt 2> /dev/null)" != "" ]; then
        yaourt -Syua --noconfirm
      else
        sudo pacman -Syu --noconfirm
      fi
      sudo pacman-db-upgrade
      ;;

    *)
      if [ "$(which echomd 2> /dev/null)" = "" ]; then
        source <(curl -s archibold.io/utils/echomd)
      fi
      echomd '
# archibold.io

  Simplified *Arch Linux* Operations
  #grey(https://www.archlinux.org/)

  #green(Usage):    archibold [option]

  #green(System Options):
  archibold *clean*             #grey(clean and optimize db cache)
  archibold *reset-keys*        #grey(earse and refresh db keys)
  archibold *update*            #grey(update all installed packages)

  #green(Packages Options):           Coming Soon
  archibold *search*  $SWNAME   #grey(search for generic software)
  archibold *install* $SWNAME   #grey(install generic software)
  archibold *remove*  $SWNAME   #grey(uninstall generic software)

'
    ;;

  esac
}
