#!/usr/bin/env bash

#########################
# archibold.io (C) 2016 #
#########################

if [ "$(which sudo 2> /dev/null)" = "" ]; then
  bash <(curl -s archibold.io/install/sudo)
fi

if [ "$(which echomd 2> /dev/null)" = "" ]; then
  bash <(curl -s archibold.io/install/echomd)
fi

archibold() {
  local TMP=
  case $1 in

    clean)
      sudo pacman -R --noconfirm $(sudo pacman -Qdtq)
      sudo pacman -Sc --noconfirm
      sudo pacman-optimize
      ;;

    install)
      if [ "$(which yaourt 2> /dev/null)" = "" ]; then
        sudo pacman -S --needed --noconfirm $2
      else
        yaourt -S --needed --noconfirm $2
      fi
      ;;

    remove)
      if [ "$(which yaourt 2> /dev/null)" = "" ]; then
        sudo pacman -Rc $2
      else
        yaourt -Rc $2
      fi
      ;;

    reset-keys)
      sudo dirmngr </dev/null
      sudo pacman -Sy --noconfirm
      sudo pacman-key -u
      sudo pacman-key --populate archlinux
      sudo pacman-key --refresh-keys
      ;;

    search)
      if [ "$(which yaourt 2> /dev/null)" = "" ]; then
        sudo pacman -Ss $2
      else
        yaourt -Ss $2
      fi
      TMP=$(curl -Ls archibold.io/install | grep $2)
      if [ "$TMP" != "" ]; then
        echomd "
# archibold.io version
bash <(curl -s archibold.io/install/$2)
"
      fi
      ;;

    update)
      if [ "$(which archibold 2> /dev/null)" != "" ]; then
        TMP="$(which archibold)"
        cd /tmp
        curl -LOs archibold.io/utils/archibold
        if [ -f archibold ]; then
          echo 'archibold "$@"' >> archibold
          chmod a+x archibold
          sudo mv archibold $TMP
        fi
        cd -
      fi
      if [ "$(which yaourt 2> /dev/null)" != "" ]; then
        yaourt -Syua --noconfirm
      else
        sudo pacman -Syu --noconfirm
      fi
      sudo pacman-db-upgrade
      ;;

    upgrade)
      archibold update && archibold clean
      ;;

    *)
      echomd '
# archibold.io

  Simplified *Arch Linux* Operations
  #grey(https://www.archlinux.org/)

  #green(Usage):    archibold [option]

  #green(System Options):
  archibold *clean*             #grey(clean and optimize db cache)
  archibold *reset-keys*        #grey(earse and refresh db keys)
  archibold *update*            #grey(update all installed packages)
  archibold *upgrade*           #grey(alias for update and clean)

  #green(Packages Options):
  archibold *search*  $SWNAME   #grey(search for generic software)
  archibold *install* $SWNAME   #grey(install generic software)
  archibold *remove*  $SWNAME   #grey(uninstall generic software)

'
    ;;

  esac
}
