#!/usr/bin/env bash

###############################################################################
# archibold.io (c) 2019 Andrea Giammarchi - ISC License                       #
###############################################################################
#
# this is similar to systemd-ask-password except it works with Delete char too
# and it's suitable to ask passwords via initcpio hooks
#
# example
#   PASS=$(askPassword "Please enter \033[1m${USER}\033[0m password:")
#
# F.A.Q.
# * why bash and not just sh ?
#     because it's easier to have modern bash in macOS (brew install bash)
# * why not just systemd-ask-password ?
#     because it doesn't really work with initcpio hooks or it breaks on DEL
# _____________________________________________________________________________

askPassword() {
  local C=""
  local W=""
  local X=""
  local PASSWORD=""
  local PROMPT="$1"
  if [ "$PROMPT" = "" ]; then
    PROMPT="\033[1mPassword:\033[0m"
  fi
  echo -ne "$PROMPT " > /dev/stderr
  while read -r -s -n1 C
  do
    X=$(printf '%x' "'$C")
    if [ "$X" = "0" ] || [ "$X" = "a" ] || [ "$X" = "d" ]; then
      break
    elif [ "$X" = "7f" ] || [ "$X" = "1b" ]; then
      if [ "$X" = "1b" ]; then
        while read -r -s -t 0.01 -n1 C
        do
          :
        done;
      fi
      if [ "$W" != "" ]; then
        W="${W:0:-1}"
        PASSWORD="${PASSWORD:0:-1}"
      fi
    else
      W="${W}*"
      PASSWORD="${PASSWORD}${C}"
    fi
    echo -ne "\033[2K\r$PROMPT $W" > /dev/stderr
  done
  echo -e "\r" > /dev/stderr
  echo "$PASSWORD"
}
