#!/usr/bin/env sh

#########################
# (c) archibold.io 2019 #
#########################

aur() {
  local pkg=""
  local preserve=""
  local skippgp=""
  if [ "${3}" = "--no-pgp" ] || [ "${2}" = "--no-pgp" ] || [ "${1}" = "--no-pgp" ]; then
    skippgp="--skippgpcheck"
  fi
  if [ "${3}" = "--preserve" ] || [ "${2}" = "--preserve" ] || [ "${1}" = "--preserve" ]; then
    preserve="--preserve"
  fi
  pkg="${1}"
  if [ "${pkg}" = "--no-pgp" ] || [ "${pkg}" = "--preserve" ]; then
    pkg="${2}"
    if [ "${pkg}" = "--no-pgp" ] || [ "${pkg}" = "--preserve" ]; then
      pkg="${3}"
    fi
  fi
  if [ "${pkg}" = "" ]; then
    echo ""
    echo "The $(tput bold)aur$(tput sgr0) utility, from https://archibold.io"
    echo "$(tput dim)A minimalistic AUR installer alternative.$(tput sgr0)"
    echo ""
    echo "  aur pakku"
    echo "  aur --preserve wpewebkit"
    echo "  aur --no-pgp expressvpn"
    echo ""
    echo "$(tput dim)Use $(tput sgr0)--preserve$(tput dim) to avoid removing the folder once built,"
    echo "which is specially useful when things don't go as expected.$(tput sgr0)"
    echo ""
    echo "$(tput dim)Use $(tput sgr0)--no-pgp$(tput dim) to ignore PGP keys $(tput sgr0)at your own risk"
    echo ""
  elif [ "$USER" = "root" ]; then
    echo ""
    echo "You $(tput bold)cannot be root$(tput sgr0) to run $(tput bold)aur$(tput sgr0)"
    echo ""
  else
    if [ ! -f ~/.archibold-aur ]; then
      date > ~/.archibold-aur
      echo "Installing $(tput bold)base-devel$(tput sgr0) and $(tput bold)git$(tput sgr0)"
      su -c 'pacman -S --needed --noconfirm base-devel git'
    fi
    rm -rf ~/tmp-${pkg}
    mkdir -p ~/tmp-${pkg}
    cd ~/tmp-${pkg}
    git clone https://aur.archlinux.org/${pkg}.git
    cd ${pkg}
    makepkg -Asfc --needed --noconfirm ${skippgp}
    echo ""
    if [ "$?" = "0" ] && [ "$(ls ${pkg}*.pkg.tar.xz 2> /dev/null)" != "" ]; then
      echo "$(tput bold)Created$(tput sgr0): ~/tmp-${pkg}/${pkg}/$(ls ${pkg}*.pkg.tar.xz)"
      sleep 1
      su -c "pacman -U --noconfirm $(ls ${pkg}*.pkg.tar.xz)"
    else
      echo "$(tput bold)Error$(tput sgr0) $?: ${pkg}*.tar.xz not found"
    fi
    if [ "${preserve}" != "--preserve" ]; then
      echo "cleaning up"
      rm -rf ~/tmp-${pkg}
    fi
    echo ""
  fi
}

aur "${1}" "${2}" "${3}"
