#!/usr/bin/env bash

#########################
# archibold.io (C) 2018 #
#########################

# if there are no arguments
if [ $# -eq 0 ]; then
  # if there is nothing piped
  if [ -t 0 ]; then
    # show the clipboard content
    xsel --clipboard --output
  else
    # pipe any input into the clipboard
    cat | xsel --clipboard --input
  fi
# pipe all arguments into the clipboard
else
  echo "$@" | xsel --clipboard --input
fi
