#!/usr/bin/env bash

partid() {
  local type="$2"
  local disk="$1"
  local length=${#disk}
  local list="$(ls ${disk}* 2> /dev/null)"
  local found=
  local info=
  if [ "$type" = "" ]; then
    if [ "$list" = "$disk" ]; then
      if [ "$(blkid -o value "$disk")" = "" ]; then
        for info in $(lsblk --output UUID "$disk"); do
          if [ "$found" = "true" ]; then
            echo $info
            break
          else
            found=true
          fi
        done
      else
        for info in $(blkid -o value "$disk"); do
          echo $info
          break
        done
      fi
    else
      if [ "$(blkid -o value "$disk")" = "" ]; then
        lsblk --output NAME,UUID,FSTYPE "$disk"
      else
        for info in $(blkid); do
          if [ "${info:0:$length}" = "$disk" ] && [ "${info:0:-1}" != "$disk" ]; then
            blkid "${info:0:-1}"
          fi
        done
      fi
    fi
  else
    if [ "$(blkid -o value "$disk")" = "" ]; then
      for info in $(lsblk --output FSTYPE,UUID "$disk"); do
        if [ "$info" = "$type" ]; then
          found=true
        elif [ "$found" = "true" ]; then
          echo $info
          break
        fi
      done
    else
      for info in $(blkid); do
        if [ "${info:0:$length}" = "$disk" ] && [ "${info:0:-1}" != "$disk" ]; then
          for info in $(blkid -o value "${info:0:-1}"); do
            if [ "$info" = "$type" ]; then
              echo "$found"
              break
            fi
            found="$info"
          done
        fi
      done
    fi
  fi
}

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "" ]; then
  echo ''
  echo 'example:'
  echo '  partid /dev/sda vfat'
  echo '  partid /dev/mmcblk0 swap'
  echo '  partid /dev/mmcblk0p3'
  echo ''
else
  partid "$1" "$2"
fi
