#!/usr/bin/env bash

partid() {
  local found=0
  if [ "$2" = "" ]; then
    lsblk --output NAME,FSTYPE,UUID "$1"
  else
    for kind in $(lsblk --output FSTYPE,UUID "$1"); do
      if [ "$kind" = "$2" ]; then
        found=1
      elif [ "$found" = "1" ]; then
        echo $kind
        break
      fi
    done
  fi
}

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "" ]; then
  echo 'partid /dev/sda vfat'
  echo 'partid /dev/sda swap'
  echo 'partid /dev/sda ext4'
else
  partid "$1" "$2"
fi
