#!/usr/bin/env bash

#########################
# (c) archibold.io 2018 #
#########################

if [ "${1}" = "" ]; then
  echo "$(tput bold)so$(tput sgr0) utility"
  echo "a lightweight sudo alternative"
  echo "fully based on bash."
  echo ""
  echo "so echo 'an echo test'"
  echo ""
else
  args=""
  for arg in "${@:2}"; do
    args="${args} \"$(echo "${arg}" | sed 's/[`$"\\]/\\\0/g')\""
  done
  su -c "${1}${args}"
fi
