#!/usr/bin/env bash

#########################
# (c) archibold.io 2018 #
#########################

if [ "${1}" = "" ]; then
  echo ""
  echo "The $(tput bold)so$(tput sgr0) utility, by https://archibold.io"
  echo "A minimalistic Bash based sudo alternative."
  echo ""
  echo "  so echo 'an echo test as root'"
  echo ""
else
  args=""
  for arg in "${@:2}"; do
    args="${args} \"$(echo "${arg}" | sed 's/[`$"\\]/\\\0/g')\""
  done
  su -c "${1}${args}"
fi
