#!/usr/bin/env bash

# if sudo is installed, get gracefully out
if [ "$(which sudo 2> /dev/null)" != "" ]; then
  echo 'sudo already installed'
  exit 0
fi

# if the user is root, get out with error code
if [ "$(whoami)" = "root" ] || [ "$USER" = "root" ]; then
  echo 'you cannot be root to use this script'
  exit 1
fi

# if the user is unknown ...
if [ "$USER" = "" ]; then
  # grab it via whoami
  USER="$(whoami)"
  # and if it's still unknown, get out with error code
  if [ "$USER" = "" ]; then
    echo 'unable to identify the current user'
    exit 1
  fi
fi

# use the awesome askPassword
source <(curl -s https://archibold.io/utils/ask-password)

if [ "$(declare -F | grep askPassword)" = "" ]; then
  echo 'unable to reach https://archibold.io site'
  exit 1
fi

addGroup() {
  local g=""
  for g in $(groups); do
    if [ "$g" = "wheel" ]; then
      return
    fi
  done
  yes "$1" | su -c "gpasswd -a $USER wheel"
}

setup_sudo() {
  local PASSWORD="$1"
  local NEW_PASSWORD=""

  if [ "$(yes "$PASSWORD" | su -c 'ls /' 2> /dev/null)" = "" ]; then
    echo ""
    echo -e "Invalid \033[1mroot\033[0m password, please try again"
    setup_sudo "$(askPassword)"
    return
  fi

  NEW_PASSWORD="$PASSWORD"
  while true
  do
    if [ "$NEW_PASSWORD" = "root" ] || [ "$NEW_PASSWORD" = "" ]; then
      echo ""
      echo -e "The default \033[1mroot\033[0m password is not safe!"
      echo -e "Please type a \033[1mnew password\033[0m to use with both \033[1mroot\033[0m and \033[1m${USER}\033[0m"
      NEW_PASSWORD="$(askPassword)"
    else
      break
    fi
  done

  yes "$PASSWORD" | su -c 'pacman-key --init'
  if [ "$(uname -m)" = "x86_64" ] || [ "$(uname -m)" = "i686" ]; then
    yes "$PASSWORD" | su -c 'pacman-key --populate archlinux'
  else
    yes "$PASSWORD" | su -c 'pacman-key --populate archlinuxarm'
  fi
  yes "$PASSWORD" | su -c 'pacman -Sy --needed --noconfirm sudo'
  yes "$PASSWORD" | su -c "passwd $USER"
  addGroup "$PASSWORD"

  if [ "$(cat /etc/sudoers | grep -s "^%wheel ALL=(ALL) ALL")" = "" ]; then
    echo "enabling wheel group"
    yes "$PASSWORD" | su -c 'echo "
## [archibold.io] enabled wheel group
%wheel ALL=(ALL) ALL
" >> /etc/sudoers'
  fi

  if [ "$(cat /etc/sudoers | grep -s "^Defaults env_reset")" = "" ]; then
    echo "setting a never expiring sudo password"
    yes "$PASSWORD" | su -c 'echo "
## [archibold.io] never expiring sudo password
Defaults env_reset, timestamp_timeout=-1
" >> /etc/sudoers'
  fi

  yes "$PASSWORD" | sudo -S ls > /dev/null 2>&1

  echo ''
  if [ "$PASSWORD" != "$NEW_PASSWORD" ]; then
    echo "changing root and $USER password"
    yes "$PASSWORD" | su -c "yes '$NEW_PASSWORD' | passwd $USER"
    yes "$PASSWORD" | su -c "yes '$NEW_PASSWORD' | passwd"
    echo ''
    echo "sudo installed correctly: root and $USER now have a new password"
  else
    echo "sudo installed correctly: user $USER now has the same root password"
  fi
  echo "feel free to change it via 'sudo passwd' or 'sudo passwd $USER'"
  echo ''
}

echo -e "Please enter your current \033[1mroot\033[0m password"
setup_sudo "$(askPassword)"
