#!/usr/bin/env bash

installPackage() {
  local package="$1"
  if [ "$(pacman -Ss $package)" != "" ]; then
    if [ "$USER" = "root" ]; then
      yes y | pacman -S --needed $package
    else
      yes y | sudo pacman -S --needed $package
    fi
  fi
}

installPackage "linux-rpi"
installPackage "linux-rpi-headers"
installPackage "raspberrypi-bootloader"
installPackage "raspberrypi-firmware"

# Note: this is done automatically - not needed
# if [ "$USER" = "root" ]; then
#   sed -i 's/mmcblk1/mmcblk0/g' /etc/fstab
# else
#   sudo sh -c "sed -i 's/mmcblk1/mmcblk0/g' /etc/fstab"
# fi
