#!/usr/bin/env bash

if [ "$(uname -m)" = "aarch64" ]; then
  if [ "$(pacman -Qs linux-raspberrypi4)" = "" ]; then
    if [ "$USER" = "root" ]; then
      yes y | pacman -S linux-raspberrypi4
      sed -i 's/mmcblk1/mmcblk0/g' /etc/fstab
    else
      yes y | sudo pacman -S linux-raspberrypi4
      sudo sh -c "sed -i 's/mmcblk1/mmcblk0/g' /etc/fstab"
    fi
    echo "Done! Remember to reboot"
  else
    echo "Nothing to do"
  fi
else
  echo "Wrong architecture: $(uname -m)"
  exit 1
fi
