#!/usr/bin/env bash

#########################
# archibold.io (C) 2021 #
#########################

if [ "$USER" = "root" ]; then
  echo 'Unable to install as root'
  exit 1
fi

if [ "$(which sudo 2> /dev/null)" = "" ]; then
  bash <(curl -s https://archibold.io/install/sudo)
fi

if [ -f /boot/boot.txt ] && [ "$(cat /boot/boot.txt | grep 'rootwait quiet')" = "" ]; then
  while ! sudo pacman -S --needed --noconfirm uboot-tools
  do
    :
  done
  sudo sed -i 's/rootwait/rootwait quiet loglevel=0/' /boot/boot.txt
  sudo mkimage -T script -C none -n 'Raspberry Pi' -d /boot/boot.txt /boot/boot.scr
fi

if [ -f /boot/cmdline.txt ] && [ "$(cat /boot/cmdline.txt | grep 'rootwait quiet')" = "" ]; then
  sudo sed -i 's/rootwait/rootwait quiet loglevel=0/' /boot/cmdline.txt
fi

if [ "$(cat /boot/config.txt | grep 'dtoverlay=vc4')" = "" ]; then
  sudo sh -c "echo 'dtoverlay=vc4-kms-v3d'>>/boot/config.txt"
fi

if [ "$(cat /boot/config.txt | grep followkernel)" = "" ]; then
  sudo sh -c "echo 'initramfs initramfs-linux.img followkernel'>>/boot/config.txt"
fi

if [ "$(cat /boot/config.txt | grep disable_splash)" = "" ]; then
  sudo sh -c "echo '
dtparam=audio=on
dtparam=spi=on
dtparam=i2c_arm=on
dtparam=i2c=on

avoid_warnings=1
disable_splash=1
disable_overscan=1
boot_delay=0
'>>/boot/config.txt"
fi

if [ "$(pacman -Qs linux-raspberrypi4)" = "" ] && [ "$(uname -m)" = "aarch64" ] && [ "$(cat /boot/config.txt | grep enable_uart)" = "" ]; then
  sudo sh -c "echo 'enable_uart=1'>>/boot/config.txt"
fi
