#!/usr/bin/env bash

#########################
# archibold.io (C) 2021 #
#########################

if [ "$USER" = "root" ]; then
  echo 'Unable to install as root'
  exit 1
fi

if [ "$(which sudo 2> /dev/null)" = "" ]; then
  bash <(curl -s https://archibold.io/install/sudo)
fi

if [ "$(which timedatectl 2> /dev/null)" != "" ]; then
  sudo timedatectl set-timezone "$(curl --fail https://ipapi.co/timezone)"
else
  clear
  echo 'WARNING: unable to set /etc/localtime'
  exit 1
fi

sudo pacman -S --needed --noconfirm geoclue gst-libav gst-plugins-bad gst-plugins-good

if [ "$(pacman -Ssq wpewebkit | grep ^wpewebkit$)" != "" ]; then
  sudo pacman -S --needed --noconfirm wpewebkit
elif [ "$(pacman -Qmq wpewebkit-bin 2> /dev/null)" = "" ]; then
  if [ "$(which aur 2> /dev/null)" = "" ]; then
    bash <(curl -s https://archibold.io/install/aur)
  fi
  aur --no-pgp wpewebkit-bin
fi

if [ "$(pacman -Ssq cog | grep ^cog$)" != "" ]; then
  sudo pacman -S --needed --noconfirm cog
else
  if [ "$(which aur 2> /dev/null)" = "" ]; then
    bash <(curl -s https://archibold.io/install/aur)
  fi
  aur --no-pgp cog
fi

if [ ! -f ~/wpe ]; then
  echo '#!/usr/bin/env sh

COG_PLATFORM_FDO_VIEW_FULLSCREEN=1 cog -P fdo https://archibold.io/demo/jellyfish/
# COG_PLATFORM_FDO_VIEW_FULLSCREEN=1 cog -P fdo https://www.youtube.com/
' >~/wpe
  chmod a+x ~/wpe
fi

bash <(curl -s https://archibold.io/install/weston)
sudo usermod -a -G wheel,games,power,optical,storage,scanner,lp,audio,video,render,weston-launch ${USER}

if [ ! -f ~/.config/weston.ini ]; then
  mkdir -p ~/.config
  echo "[core]
idle-time=0
repaint-window=15
require-input=false

[shell]
client=${HOME}/wpe
animation=none
close-animation=none
startup-animation=none
locking=false

[output]
name=
mode=
">~/.config/weston.ini
fi
